check_http: Update to new framework and pull from archive create_html: Update output_html variable run_monitors: Add HTTP monitor type

diff --git a/monitoring/check_http b/monitoring/check_http
--- a/monitoring/check_http
+++ b/monitoring/check_http
@@ -1,40 +1,16 @@
 #!/bin/bash
 
-HTTP_HOSTS=""
+SCRIPT_PATH=$(dirname $(realpath $BASH_SOURCE))
 
-. $APP_HOME/common_functions.sh
+. "$SCRIPT_PATH/common.sh"
 
-for entry in $HTTP_HOSTS; do
-  url=$entry
-  sname=$(sanitize_varsV2 $url)
-  last_status=$(get_last_statusV2 $sname "HTTP")
+[[ -z $1 ]] && echo "usage: $0 <url>" >&2 && exit 1
 
-  port=80
-  protocol=$(echo $url |cut -d: -f1)
-  host=$(echo $url |sed -r -e 's/^.+:\/\///' -e 's/^([a-zA-Z0-9\-\.:]+).*/\1/')
+url=$1
 
-  if [[ "$protocol" == "https" ]]; then
-    port=443
-    ssl_opt="-S"
-  fi
-
-  set +e
-  curl -k -s -m 5 -o /dev/null $url
-  if [[ $? -ne 0 ]]; then
-    if [[ "$last_status" != "BAD" ]]; then
-      send_notice "HTTP Status for $url" "Check failed for $url"
-    fi
-    new_status="BAD"
-    new_state="Down"
-  else
-    if [[ "$last_status" != "OK" ]]; then
-      send_notice "HTTP Status for $url" "Check OK for $url"
-    fi
-    new_status="OK"
-    new_state="Up"
-  fi
-  set -e
-
-  record_status $sname "HTTP" $new_status "$new_state"
-done
+if curl -s -I -o /dev/null "$url"; then
+  echo "OK;Good HTTP Response"
+else
+  echo "BAD;Error fetching URL"
+fi
 
